### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by toadyus** [aaearon/ss-plex-proxy#7]
Getting the following error, just started happening yesterday.

[2021-08-28 22:30:35,007] INFO in guide: Creating stream url with scheme "https", server "<SS Server>", port "443", playlist ".stream/mpeg.2ts"
[2021-08-28 22:30:35,007] WARNING in auth: Hash is either none or may be expired. Getting a new one...
[2021-08-28 22:30:35,007] DEBUG in auth: Username and password are not none.
[2021-08-28 22:30:35,007] DEBUG in auth: Getting hash using hash API
[2021-08-28 22:30:35,008] DEBUG in auth: Fetching hash at https://auth.smoothstreams.tv/hash_api.php?username=<username>&site=<site>&password=<password>
INFO:werkzeug:192.168.1.65 - - [28/Aug/2021 22:30:35] "GET /channels/12 HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/toad/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/toad/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/toad/.local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toad/Aaearon/ss-plex-proxy.py", line 29, in get_channel
    url = guide.build_stream_url(
  File "/home/toad/.local/lib/python3.8/site-packages/pysmoothstreams/guide.py", line 192, in build_stream_url
    auth_sign=auth_sign.fetch_hash(),
  File "/home/toad/.local/lib/python3.8/site-packages/pysmoothstreams/auth.py", line 75, in fetch_hash
    self._get_hash_via_hash_api()
  File "/home/toad/.local/lib/python3.8/site-packages/pysmoothstreams/auth.py", line 51, in _get_hash_via_hash_api
    with urllib.request.urlopen(hash_url) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by aaearon** [comment]
It looks like they have implemented some user agent whitelisting as I have tried from Chrome and it worked fine. I went ahead and set a custom user agent to be sent when fetching the hash api as part of https://github.com/aaearon/pysmoothstreams/releases/tag/0.16.

I've asked them to whitelist the user agent and am waiting on a response.

**Comment by aaearon** [comment]
Closed with https://github.com/aaearon/ss-plex-proxy/commit/5d787f8d859201a334b3e026b010c3b801cdea04

**Comment by toadyus** [comment]
Yup....Issue has been resolved! Thank you!!
